/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAgentStopRouteImport } from './routes/api/agent/stop'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent/run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStopRoute = ApiAgentStopRouteImport.update({
  id: '/api/agent/stop',
  path: '/api/agent/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/agent/run'
    | '/api/agent/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/agent/run'
    | '/api/agent/stop'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/agent/run'
    | '/api/agent/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiAgentStopRoute: typeof ApiAgentStopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stop': {
      id: '/api/agent/stop'
      path: '/api/agent/stop'
      fullPath: '/api/agent/stop'
      preLoaderRoute: typeof ApiAgentStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiAgentStopRoute: ApiAgentStopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
