/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocNameRouteImport } from './routes/doc/$name'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiYjsSplatRouteImport } from './routes/api/yjs/$'
import { Route as ApiAgentStopRouteImport } from './routes/api/agent/stop'
import { Route as ApiYjsDocsSplatRouteImport } from './routes/api/yjs/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocNameRoute = DocNameRouteImport.update({
  id: '/doc/$name',
  path: '/doc/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYjsSplatRoute = ApiYjsSplatRouteImport.update({
  id: '/api/yjs/$',
  path: '/api/yjs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStopRoute = ApiAgentStopRouteImport.update({
  id: '/api/agent/stop',
  path: '/api/agent/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYjsDocsSplatRoute = ApiYjsDocsSplatRouteImport.update({
  id: '/api/yjs/docs/$',
  path: '/api/yjs/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/doc/$name': typeof DocNameRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
  '/api/yjs/$': typeof ApiYjsSplatRoute
  '/api/yjs/docs/$': typeof ApiYjsDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/doc/$name': typeof DocNameRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
  '/api/yjs/$': typeof ApiYjsSplatRoute
  '/api/yjs/docs/$': typeof ApiYjsDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/doc/$name': typeof DocNameRoute
  '/api/agent/stop': typeof ApiAgentStopRoute
  '/api/yjs/$': typeof ApiYjsSplatRoute
  '/api/yjs/docs/$': typeof ApiYjsDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/doc/$name'
    | '/api/agent/stop'
    | '/api/yjs/$'
    | '/api/yjs/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/doc/$name'
    | '/api/agent/stop'
    | '/api/yjs/$'
    | '/api/yjs/docs/$'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat-stream'
    | '/doc/$name'
    | '/api/agent/stop'
    | '/api/yjs/$'
    | '/api/yjs/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  DocNameRoute: typeof DocNameRoute
  ApiAgentStopRoute: typeof ApiAgentStopRoute
  ApiYjsSplatRoute: typeof ApiYjsSplatRoute
  ApiYjsDocsSplatRoute: typeof ApiYjsDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$name': {
      id: '/doc/$name'
      path: '/doc/$name'
      fullPath: '/doc/$name'
      preLoaderRoute: typeof DocNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yjs/$': {
      id: '/api/yjs/$'
      path: '/api/yjs/$'
      fullPath: '/api/yjs/$'
      preLoaderRoute: typeof ApiYjsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stop': {
      id: '/api/agent/stop'
      path: '/api/agent/stop'
      fullPath: '/api/agent/stop'
      preLoaderRoute: typeof ApiAgentStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yjs/docs/$': {
      id: '/api/yjs/docs/$'
      path: '/api/yjs/docs/$'
      fullPath: '/api/yjs/docs/$'
      preLoaderRoute: typeof ApiYjsDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  DocNameRoute: DocNameRoute,
  ApiAgentStopRoute: ApiAgentStopRoute,
  ApiYjsSplatRoute: ApiYjsSplatRoute,
  ApiYjsDocsSplatRoute: ApiYjsDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
